# Generated by Django 4.2.7 on 2023-11-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[['male', 'male'], ['female', 'female'], ['other', 'other']], max_length=50, null=True),
        ),
    ]
