# Generated by Django 4.2.7 on 2023-11-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
