# Generated by Django 4.2.7 on 2023-11-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='value',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='var_category',
        ),
        migrations.AddField(
            model_name='variation',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
