# Generated by Django 4.2.7 on 2023-11-22 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_cart_cartitem_carts_alter_cartitem_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='carts',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='cart.cart'),
        ),
    ]
