# Generated by Django 4.2.7 on 2023-11-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('cart', '0005_remove_cartitem_variation_cartitem_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(null=True, related_name='variation', to='store.variation'),
        ),
    ]
