# Generated by Django 4.2.7 on 2023-11-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_variation_value_remove_variation_var_category_and_more'),
        ('cart', '0007_remove_cartitem_variation_cartitem_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='store.variation'),
        ),
    ]
