# Generated by Django 4.2.7 on 2023-11-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_id_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Deliverred', 'Delivered'), ('Cancaled', 'Cancaled'), ('Ongoing', 'Ongoing')], default='New', max_length=10),
        ),
    ]
