# Generated by Django 4.2.7 on 2023-11-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Deliverred', 'Delivered'), ('Cancaled', 'Cancaled'), ('Ongoing', 'Ongoing')], default='New', max_length=10),
        ),
    ]
